<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $trip->title }} - Trip Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #374151; line-height: 1.5; font-size: 13px; margin: 0; padding: 0; }
        .page-break { page-break-after: always; }
        
        /* Cover Page */
        .cover-page { text-align: center; margin-top: 150px; }
        .cover-title { font-size: 36px; font-weight: bold; color: #111827; margin-bottom: 10px; }
        .cover-subtitle { font-size: 18px; color: #4f46e5; margin-bottom: 50px; }
        .cover-meta { font-size: 14px; color: #6b7280; }
        
        /* General Layout */
        .header-bar { border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; color: #111827; font-size: 20px; }
        .date-header { background: #f3f4f6; padding: 8px 12px; font-weight: bold; margin-top: 20px; border-left: 4px solid #4f46e5; color: #1f2937; }
        
        /* Itinerary */
        .activity { padding: 12px 0; border-bottom: 1px solid #e5e7eb; display: table; width: 100%; }
        .time { display: table-cell; font-weight: bold; width: 90px; color: #4f46e5; }
        .content { display: table-cell; }
        .title { font-weight: bold; font-size: 14px; color: #111827; }
        .details { color: #6b7280; font-size: 12px; margin-top: 3px; }
        
        /* Tables (Finances & Packing) */
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f9fafb; text-align: left; padding: 10px; font-size: 12px; color: #374151; border-bottom: 2px solid #e5e7eb; }
        td { padding: 10px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
        .amount { text-align: right; font-weight: bold; }
        
        /* Totals Card */
        .summary-box { background: #f3f4f6; padding: 15px; border-radius: 5px; margin-bottom: 20px; text-align: right; }
        .summary-box h3 { margin: 0 0 5px 0; color: #111827; }
        
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #9ca3af; }
    </style>
</head>
<body>
    <!-- Footer on all pages -->
    <div class="footer">
        Generated by {{ $exportUser->name }} on {{ now()->format('M d, Y') }} via TripPlanner
    </div>

    <!-- Cover Page -->
    <div class="cover-page page-break">
        <h1 class="cover-title">{{ $trip->title }}</h1>
        <div class="cover-subtitle">{{ $trip->destination }}</div>
        
        <div class="cover-meta">
            <p><strong>Travel Dates:</strong> <br>{{ \Carbon\Carbon::parse($trip->start_date)->format('F j, Y') }} — {{ \Carbon\Carbon::parse($trip->end_date)->format('F j, Y') }}</p>
            <br><br>
            <p><strong>Prepared for:</strong> <br>The {{ $trip->title }} Travel Group</p>
        </div>
    </div>

    <!-- Section: Itinerary -->
    @if(in_array('itinerary', $sections))
        <div class="header-bar">
            <h2>Official Itinerary</h2>
        </div>
        
        @forelse ($groupedActivities as $date => $activities)
            <div class="date-header">
                {{ \Carbon\Carbon::parse($date)->format('l, F j, Y') }}
            </div>
            
            @foreach ($activities as $activity)
                <div class="activity">
                    <div class="time">{{ \Carbon\Carbon::parse($activity->scheduled_at)->format('g:i A') }}</div>
                    <div class="content">
                        <div class="title">{{ $activity->title }} <span style="font-weight: normal; color: #6b7280; font-size: 12px;">({{ ucfirst($activity->type) }})</span></div>
                        @if($activity->location)
                            <div class="details"><strong>Location:</strong> {{ $activity->location }}</div>
                        @endif
                        @if($activity->reservation_code)
                            <div class="details"><strong>Reservation #:</strong> {{ $activity->reservation_code }}</div>
                        @endif
                        @if($activity->notes)
                            <div class="details"><strong>Notes:</strong> {{ $activity->notes }}</div>
                        @endif
                    </div>
                </div>
            @endforeach
        @empty
            <p style="text-align: center; margin-top: 30px; color: #6b7280;">No activities planned yet.</p>
        @endforelse
        
        <!-- Add a page break if there are more sections coming -->
        @if(in_array('finances', $sections) || in_array('packing', $sections))
            <div class="page-break"></div>
        @endif
    @endif

    <!-- Section: Finances -->
    @if(in_array('finances', $sections))
        <div class="header-bar">
            <h2>Financial Summary</h2>
        </div>

        <div class="summary-box">
            <h3>Total Shared Cost: ${{ number_format($sharedTotal, 2) }}</h3>
            <p style="margin: 0; color: #4b5563;">Cost per person ({{ $memberCount }} travelers): <strong>${{ number_format($sharedTotal / $memberCount, 2) }}</strong></p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Paid By</th>
                    <th>Type</th>
                    <th class="amount">Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse($expenses as $expense)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($expense->date)->format('M d, Y') }}</td>
                        <td>{{ $expense->description }}</td>
                        <td>{{ $expense->payer->name }}</td>
                        <td>{{ $expense->is_personal ? 'Personal' : 'Group' }}</td>
                        <td class="amount">${{ number_format($expense->amount, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" style="text-align: center; color: #6b7280;">No expenses logged.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        @if(in_array('packing', $sections))
            <div class="page-break"></div>
        @endif
    @endif

    <!-- Section: Packing List -->
    @if(in_array('packing', $sections))
        <div class="header-bar">
            <h2>Group Packing List</h2>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 40px;">Me</th>
                    <th>Item</th>
                    <th>Packed By</th>
                </tr>
            </thead>
            <tbody>
                @forelse($packingList as $item)
                    @php 
                        // Check if the person exporting the PDF has packed this
                        $packedByMe = $item->packedBy->contains($exportUser->id); 
                        $packedByNames = $item->packedBy->pluck('name')->implode(', ');
                    @endphp
                    <tr>
                        <td style="font-family: monospace; font-size: 16px; font-weight: bold; color: {{ $packedByMe ? '#10b981' : '#d1d5db' }};">
                            [{{ $packedByMe ? 'X' : ' ' }}]
                        </td>
                        <td style="font-weight: bold;">{{ $item->item }}</td>
                        <td style="color: #6b7280; font-size: 11px;">
                            {{ $packedByNames ?: 'No one yet' }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" style="text-align: center; color: #6b7280;">Packing list is empty.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    @endif
</body>
</html>